# Generated by Django 4.0.3 on 2022-09-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'ordering': ['title', 'time_create'], 'verbose_name': 'Артисты', 'verbose_name_plural': 'Артисты'},
        ),
    ]
